const questionsOfArt = [
    [
        {
            id: 1,
            title: "Палитрой называется небольшая доска, на которой художник смешивает краски",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 2,
            title: "Сальвадора Дали на создание своей знаменитой картины «Постоянство памяти» вдохновила бывшая любовь",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 3,
            title: "На картине «Звездная ночь» Винсента Ван Гога изображено созвездие «Большая Медведица»",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 4,
            title: "Основоположником Азербайджанской драматургии является Мирза Фатали Ахундов",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 5,
            title: "Слова «Жизнь — театр, а люди — в нём актёры» принадлежат Уильяму Шекспиру",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 6,
            title: "Леонардо Да Винчи получил свой первый оскар за фильм «Выживший»",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 7,
            title: "Картина «Крик» Эдварда Мунка послужила прототипом смайлика",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 8,
            title: "Автопортрет - это изображение художником автомобиля",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 9,
            title: "Полнота оперных певцов — это миф",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 10,
            title: "Музыкальных нот всего 7",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 11,
            title: "Опера и оперетта - одно и тоже",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 12,
            title: "Палочка нужна дирижёру для того, чтобы музыканты его лучше видели",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 13,
            title: "В театр нельзя ходить в джинсах",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 14,
            title: "Синий, голубой, фиолетовый, зеленый цвета называют холодными",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 15,
            title: "Красный, оранжевый, желтый цвета называют теплыми",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 16,
            title: "Линия, выполняемая одним движением руки, называется штрихом",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 17,
            title: "Желтый, красный, синий - главные цвета",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 18,
            title: "В Греции в конце третьего тысячелетия до н.э. устраивались театральные сценки о покровителе земледельцев и ремесленников – боге Осирисе",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 19,
            title: "В Древней Греции родилось высокое искусство театра, на основе которого возник европейский театр",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 20,
            title: "Картина Рембрандта «Возвращение блудного сына» находится в Лувре",
            isShowed: false,
            isCorrect: false,
        },
    ],
    [
        {
            id: 1,
            title: "Музей Винсента Ван Гога находится в Амстердаме",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 2,
            title: "Илья Репин написал картину «Тайная вечеря»",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 3,
            title: "Орсе - это крупный музей в Париже, являющийся центром европейских изобразительных и прикладных искусств",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 4,
            title: "Виктор Васнецов написал картину «Грачи прилетели»",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 5,
            title: "«Мона Лиза» - то же самое, что и «Джоконда»",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 6,
            title: "Микеланджело - великих деятелей искусства, который не принадлежал к эпохе Возрождения",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 7,
            title: "Василий Кандинский написал знаменитый «Черный квадрат»",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 8,
            title: "Карл Росси - один из знаменитых архитекторов, который работал в России",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 9,
            title: "Художник Ян Вермеер написал картину «Девушка с жемчужной серёжкой»",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 10,
            title: "«Сад земных наслаждений» — самый известный триптих Иеронима Босха",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 11,
            title: "Ян Вермеер - датский художник-живописец",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 12,
            title: "«Моряками» называются художники, посвящающие свое творчество изображению моря",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 13,
            title: "Маринисты - это люди, которые работают исключительно с морилкой",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 14,
            title: "Светотень - это одно из основных средств изобразительного искусства, строго закономерная градация светлого и темного",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 15,
            title: "Английский философ, химик и общественный деятель Джозеф Пристли в 1770 г. создал ластик",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 16,
            title: "Кубизм зародился на Кубе",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 17,
            title: "В Иране находится архитектурный шедевр Тадж-Махал",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 18,
            title: "Ван Гог написал «Звездную ночь», находясь в психиатрической клинике",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 19,
            title: "Клод Моне и Эдуард Мане - оба были художники, жили в одно время, оба были импрессионистами и носили бороды",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 20,
            title: "Фрида Кало была актриссой",
            isShowed: false,
            isCorrect: false,
        }
    ]
];

localStorage.setItem('arrayOfQuestions', JSON.stringify(questionsOfArt[Math.floor(Math.random() * 2)]));