const questionsOfScience = [
    [   {
            id: 1,
            title: "Юпитер — шестая планета от Cолнца",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 2,
            title: "У Сатурна наибольшее количество извесных спутников среди планет солнечной системы",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 3,
            title: "Самый распространенный тип атома во Вселенной — атом углерода",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 4,
            title: "Температура плавления железа 500°",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 5,
            title: "Нагретый до высокой температуры магнит, не вернет свои магнитные свойства после остывания",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 6,
            title: "Латунь — это сплав олова и цинка",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 7,
            title: "Цвет свечения неона красно-оранжевый",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 8,
            title: "Рубидий — щелочной металл",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 9,
            title: "Солнце состоит в основном на 30% из водорода и 70% из гелия",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 10,
            title: "На Венере сутки длиннее года",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 11,
            title: "Атмосфера Марса на 95% состоит из водорода",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 12,
            title: "Масса нашей планеты увеличилась на один миллиард тонн за последние пять столетий",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 13,
            title: "Гранит проводит звук лучше, чем воздух",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 14,
            title: "Перфторбутан - самый тяжелый газ",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 15,
            title: "Горячая вода замерзает быстрее холодной",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 16,
            title: "Бор окрашивает пламя в красный цвет",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 17,
            title: "Бром может расплавиться при комнатной температуре",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 18,
            title: "Звук распространяется быстрее в плотной среде",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 19,
            title: "Свету требуется 12 минут 19 секунд, чтобы добраться от Солнца до Земли",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 20,
            title: "Венера — единственная планета, которая вращается против часовой стрелки",
            isShowed: false,
            isCorrect: false,
        },
    ],
    [   {
            id: 1,
            title: "Уран виден с Земли невооруженным глазом",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 2,
            title: "Свинец можно превратить в золото",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 3,
            title: "Через телескоп можно детально разглядеть горы и долины на Луне",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 4,
            title: "В одном литре морской воды содержится примерно 1кг соли",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 5,
            title: "Лишь 1% воды Земли является пресной",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 6,
            title: "В коллайдере может родиться черная дыра",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 7,
            title: "Россия, Франция и Дания входят в список стран, участвовавших в создании МКС",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 8,
            title: "Длина 100 миллионов атомов водорода в одной цепи составляет один сантиметр",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 9,
            title: "Хемофо́бия — боязнь химических соединений",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 10,
            title: "Молнию можно использовать как мощный источник электрической энергии",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 11,
            title: "Магнитные полюсы Земли перемещаются",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 12,
            title: "Самый большой спутник в Солнечной системе — Титан",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 13,
            title: "При соединении с йодом храхмал окрасится в синий",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 14,
            title: "Кора Земли состоит из 18 химических элементов",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 15,
            title: "Предположение о том, что Земля имеет форму шара, впервые сделал Галилей",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 16,
            title: "Криптон — инертный газ",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 17,
            title: "В Австралии нет активных вулканов",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 18,
            title: "Около 80% всех цунами случаются в Атлантическом океане",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 19,
            title: "Температура молнии превышает температуру поверхности Солнца",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 20,
            title: "Сублима́ция — конденсация вещества из газообразного состояния, минуя жидкое, непосредственно в твёрдое состояние",
            isShowed: false,
            isCorrect: false,
        },
    ],
];

localStorage.setItem('arrayOfQuestions', JSON.stringify(questionsOfScience[Math.floor(Math.random() * 2)]));