const questionsOfMedicine = [
    [{
            id: 1,
            title: "Сердце человека трехкамерное",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 2,
            title: "Астигматизм — дефект слуха",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 3,
            title: "В мозге нейронов больше, чем звезд в Млечном пути",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 4,
            title: "Человек использует только 10% своего мозга",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 5,
            title: "Левая почка тяжелее правой",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 6,
            title: "В черепе взрослого человека 53 кости",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 7,
            title: "Около 95% клеток в человеческом теле — бактерии",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 8,
            title: "В среднем за минуту дыхательная система человека потребляет около 8 литров воздуха",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 9,
            title: "Согласно статистике, кости ног ломаются чаще всего",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 10,
            title: "Мозг работает активнее, когда мы спим",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 11,
            title: "Человеческий мозг продолжает развиваться до достижения примерно 35-летнего возраста",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 12,
            title: "Кожа составляет около 15% веса тела",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 13,
            title: "Запуск стресс-реакции запускает сердечно-сосудистая система",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 14,
            title: "Генетически к человеку ближе всего свинья",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 15,
            title: "Уши растут на протяжении всей жизни",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 16,
            title: "уровень тестостерона у мужчин зависит от витамина B",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 17,
            title: "Общая протяжённость кровеносных сосудов в теле среднестатистического взрослого человека длиннее окружности Земли",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 18,
            title: "Адентия — редкое заболевание, при котором во рту растут лишние зубы",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 19,
            title: "30% всех случаев рака связаны с наследственностью",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 20,
            title: "ВИЧ — последняя стадия СПИДа",
            isShowed: false,
            isCorrect: false,
        },
    ],
    [{
            id: 1,
            title: "Нарушение ночного видения появляется при недостатке витамина A",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 2,
            title: "Самая сильная мышца по создаваемому усилию — сердце",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 3,
            title: "Полностью излечиться от шизофрении невозможно",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 4,
            title: "Мозг человека увеличиватся в размерах с течением эволюции",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 5,
            title: "В слюне содержится обезболивающее вещество, более мощное, чем морфий",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 6,
            title: "Пищеварительный мешок у взрослого человека может вместить около 4 литров пищи или воды",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 7,
            title: "У женщин обоняние развито лучше, чем у мужчин",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 8,
            title: "Сильный шум провоцирует расширение зрачков",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 9,
            title: "Человеческий мозг на 80% состоит из воды",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 10,
            title: "Делая шаг, человек приводит в действие около двухсот мышц одновременно",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 11,
            title: "Регулярное употребление кофе во время беременности может привести к выкидышу",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 12,
            title: "Волосы и ногти продолжают расти после смерти человека",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 13,
            title: "Уши играют роль в способности держать равновесие",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 14,
            title: "Гены влияют на появление лишнего веса",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 15,
            title: "Скелет человека полностью обновляется каждые три месяца",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 16,
            title: "Продолжительность общего цикла кровообращения в теле человека занимает в среднем 2 минуты",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 17,
            title: "Курение — фактор риска развития рака мочевого пузыря",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 18,
            title: "Жевательная мышца в организме человека – самая сильная по создаваемому усилию",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 19,
            title: "Человек единственное существо, у которого есть белки глаз",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 20,
            title: "Один квадратный сантиметр человеческой кожи содержит около миллиона потовых желез",
            isShowed: false,
            isCorrect: false,
        },
    ],
];