const questionsOfGeography = [
    [
        {
            id: 1,
            title: "Бердин - столица Лондона",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 2,
            title: "Америго Веспуччи был американцем",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 3,
            title: "Река Конго дважды пересекает экватор",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 4,
            title: "Атмосфера - воздушная оболочка земли",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 5,
            title: "В Австралии есть действующие вулканы",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 6,
            title: "Саванна - самая распространённая природная зона Африки",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 7,
            title: "Каспийское озеро - самое глубокое озеро мира",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 8,
            title: "Антарктида - самый ветреный материк",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 9,
            title: "Карпаты - самый длинный горный хребет",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 10,
            title: "Евразия - самый влажный материк",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 11,
            title: "Хартум - столица Египта",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 12,
            title: "Азимут - это угол между направлением на север и какой-нибудь предмет местности",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 13,
            title: "Белое море одновременно является самым теплым и самым холодным",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 14,
            title: "Гора Айленд-пик является самой дальней точкой от центра Земли",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 15,
            title: "Последний активный вулкан на планете погас в 2010 году",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 16,
            title: "Вся Арктика – это одна большая глыба льда",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 17,
            title: "Тибет - это самостоятельное государство под управлением Далай-ламы",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 18,
            title: "Остров Мадагаскар, Цейлон и Занзибар принадлежат Франции",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 19,
            title: "Нью-Дели находится в США",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 20,
            title: "Столицей Баку является Азербайджан",
            isShowed: false,
            isCorrect: false,
        },
    ],
    [
        {
            id: 1,
            title: "Земля круглая",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 2,
            title: "Остров Мадагаскар принадлежит Бельгии",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 3,
            title: "В государстве Того мужчина, сделавший комплимент женщине, обязан на ней жениться",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 4,
            title: "Название страны «Габон» означает «пальто с капюшоном»",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 5,
            title: "Город Цинциннати находится в Италии",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 6,
            title: "Пустыня Атакама расположена в южном полушарии",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 7,
            title: "Мадагаскар - это самый большой остров в мире",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 8,
            title: "Гренладия - это самый большой остров в мире",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 9,
            title: "Туркменистан – одна из 5 стран, имеющих выход к Каспийскому морю",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 10,
            title: "Развалины древнего города Карфаген находятся в Египте",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 11,
            title: "Город Шлиссельбург находится в Германии",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 12,
            title: "Стоунхедж - национальное достояние Ирландии",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 13,
            title: "Титикака - это озеро",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 14,
            title: "Столица Мадагаскар Антананариву",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 15,
            title: "Государственный флаг Непала — единственный в мире государственный флаг непрямоугольной формы",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 16,
            title: "Сидней - столица Австралии",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 17,
            title: "Земля плоская",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 18,
            title: "Соединённые Штаты Америки состоят из 49 штатов",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 19,
            title: "Северный Ледовитый океан – самый маленький по площади океан планеты",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 20,
            title: "Байкал - самое неглубокое озеро планеты",
            isShowed: false,
            isCorrect: false,
        },
    ],
];

localStorage.setItem('arrayOfQuestions', JSON.stringify(questionsOfGeography[Math.floor(Math.random() * 2)]));