const questionsOfMusic = [
    [
        {
            id: 1,
            title: "В официальный состав группы The Rolling Stones за всю ее историю входило 8 музыкантов?",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 2,
            title: "Первая в Азербайджане консерватория была основана в 1920 году?",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 3,
            title: "Реквием - это последнее, незавершённое прижизненное произведение Моцарта, над которым он работал вплоть до самой кончины?",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 4,
            title: "Скрипичный, басовый и альтовый - это три основных музыкальных ключа?",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 5,
            title: "Скорость движения музыкального произведения называют темпом?",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 6,
            title: "Можно задать темп музыкального произведения по метроному?",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 7,
            title: "Moderato относится к быстрой группе музыкальных темпов?",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 8,
            title: "Vivo относится к быстрой группе музыкальных темпов?",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 9,
            title: "Andante относится к медленной группе музыкальных темпов?",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 10,
            title: "Adagio относится к медленной группе музыкальных темпов?",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 11,
            title: "Курт Кобейн был солистом группы Metallica?",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 12,
            title: "Узеир Гаджибеков написал в 1907 году оперу «Руслан и Людмила»?",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 13,
            title: "Вагиф Мустафа-заде является основоположником азербайджанского джаза?",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 14,
            title: "Франсиско Таррега был гитаристом?",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 15,
            title: "Певица Далида родилась в Египте?",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 16,
            title: "Луиза Чикконе - это младшая сестра певицы Мадонны?",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 17,
            title: "Дженифер Лопес родилась в Бразилии?",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 18,
            title: "Муслим Магомаев был оперным певцом?",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 19,
            title: "Существует всего четыре музыкальных направления (народная музыка, духовная музыка, академическая музыка и популярная музыка), к каждому направлению принадлежит некоторое количество жанров музыки и у каждого жанра есть множество поджанров.",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 20,
            title: "Блюз - это тоже самое, что и Джаз?",
            isShowed: false,
            isCorrect: false,
        },
    ],
    [
        {
            id: 1,
            title: "В музыке всего семь нот?",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 2,
            title: "Основная роль дирижёрской палочки заключается в том, чтобы сделать движения кисти более заметными для коллектива?",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 3,
            title: "Октава - это интервал между одноименными звуками (нотами) различной высоты?",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 4,
            title: "Веерообразная рассадка музыкантов помогает им хорошо видеть дирижера, который находится в месте схода воображаемых осей веера",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 5,
            title: "Шакира - это колумбийская певица ливанского происхождения?",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 6,
            title: "Музыкальный квартет состоит из двух человек?",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 7,
            title: "Сопрано - самый высокий женский голос?",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 8,
            title: "У скрипки 5 струн",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 9,
            title: "Балалайка должна иметь три струны",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 10,
            title: "В детской песенке «В траве сидел кузнечик» поется о трагической смерти маленького насекомого",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 11,
            title: "Кот Матроскин из мультфильма «Простоквашино» всегда играл на саксофоне?",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 12,
            title: "Солист группы Рамштайн родился в ГДР",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 13,
            title: "Людвиг ван Бетховен был от рождения глухим?",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 14,
            title: "Иоганн Себастьян Бах - автор более 1000 музыкальных произведений во всех значимых жанрах своего времени (кроме оперы)",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 15,
            title: "Правда ли то, что музыкальные ноты в разное время звучали по-разному?",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 16,
            title: "Никто из участников группы «Битлз» не знал нотной грамоты",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 17,
            title: "Увертюра - это финал произведения",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 18,
            title: "Британский военно-морской флот распугивает сомалийских пиратов песнями Бритни Спирс.",
            isShowed: false,
            isCorrect: true,
        },
        {
            id: 19,
            title: "Симфонический оркестр - это группа музыкантов, играющих только на струнных инструментах",
            isShowed: false,
            isCorrect: false,
        },
        {
            id: 20,
            title: "Cамый длинный органный концерт в мире начался в 2001 году, а закончится только в 2640 году, то есть через 639 лет.",
            isShowed: false,
            isCorrect: true,
        },
    ],
];